# Generated by Django 4.2.11 on 2024-04-18 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0012_rename_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineeventobjectref",
            name="sodar_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Object reference SODAR UUID", null=True
            ),
        ),
    ]
