# Generated by Django 5.2.17 on 2026-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timeline', '0001_squashed_0015_make_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='core_version',
            field=models.TextField(
                blank=True,
                help_text='SODAR Core version on event creation',
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='site_version',
            field=models.TextField(
                blank=True,
                help_text='Site version on event creation',
                max_length=128,
            ),
        ),
    ]
