# Generated by Django 3.2.18 on 2023-03-14 10:21

from django.db import migrations

def clean_up_app_settings(apps, schema_editor):
    AppSetting = apps.get_model('projectroles', 'AppSetting')

    # Find all app settings with project type 'CATEGORY'
    app_settings = AppSetting.objects.filter(project__type='CATEGORY')
    app_settings.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0025_delete_projectusertag'),
    ]

    operations = [
        migrations.RunPython(clean_up_app_settings, reverse_code=migrations.RunPython.noop),
    ]
