# Generated by Django 3.2.18 on 2023-04-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0026_delete_category_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='project',
            field=models.ForeignKey(
                help_text='Project in which role is assigned',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='local_roles',
                to='projectroles.project'
            ),
        ),
    ]
