# Generated by Django 5.2.7 on 2025-10-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0038_update_ip_allow_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='public_guest_access',
        ),
    ]
