# Generated by Django 5.2.10 on 2026-01-13 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projectroles', '0039_remove_project_public_guest_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='user_modifiable',
        ),
    ]
