# Generated by Django 5.2.10 on 2026-01-20 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djangoplugins', '0002_auto_20230718_1254'),
        ('projectroles', '0040_remove_appsetting_user_modifiable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appsetting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='remotesite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sodaruseradditionalemail',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appsetting',
            constraint=models.UniqueConstraint(
                fields=('project', 'user', 'app_plugin', 'name'),
                name='unique_app_setting_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(
                fields=('title', 'parent'), name='unique_project_path'
            ),
        ),
        migrations.AddConstraint(
            model_name='remotesite',
            constraint=models.UniqueConstraint(
                fields=('url', 'mode', 'secret'), name='unique_remote_site'
            ),
        ),
        migrations.AddConstraint(
            model_name='sodaruseradditionalemail',
            constraint=models.UniqueConstraint(
                fields=('user', 'email'), name='unique_user_email'
            ),
        ),
    ]
