# Generated by Django 5.2.10 on 2026-02-11 15:40

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0041_alter_appsetting_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='_readme_rendered',
        ),
        migrations.RemoveField(
            model_name='project',
            name='readme_markup_type',
        ),
        migrations.AlterField(
            model_name='project',
            name='readme',
            field=martor.models.MartorField(
                blank=True,
                help_text='Project README (optional, supports markdown)',
                null=True,
            ),
        ),
    ]
