# Generated by Django 5.2.17 on 2026-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projectroles', '0042_remove_project__readme_rendered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_slug',
            field=models.CharField(
                blank=True,
                help_text='Title slug used as a human-friendly alias',
                max_length=4096,
            ),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(
                condition=models.Q(('title_slug', ''), _negated=True),
                fields=('title_slug',),
                name='unique_title_slug',
            ),
        ),
    ]
