"""Ajax views for the siteinfo app"""

import logging

from djangoplugins.point import PluginPoint

from rest_framework.response import Response

from projectroles.plugins import PluginAPI
from projectroles.templatetags.projectroles_common_tags import get_info_link
from projectroles.views_ajax import SODARBasePermissionAjaxView
from siteinfo.templatetags.siteinfo_tags import get_info_cls, get_info_val


logger = logging.getLogger(__name__)
plugin_api = PluginAPI()


class PluginStatisticsAjaxView(SODARBasePermissionAjaxView):
    """Plugin statistics retrieval ajax view"""

    permission_required = 'siteinfo.view_info'

    def _get_statistics(self, plugin: PluginPoint):
        """Get plugin stats and decorate them with extra attributes"""
        stats = plugin.get_statistics()
        for k in stats.keys():
            # We use these values in the HTML generated by this view
            if stats[k].get('description'):
                stats[k]['info_link'] = get_info_link(stats[k]['description'])
            if not stats[k].get('url'):
                stats[k]['info_cls'] = get_info_cls(stats[k]['value'])
                stats[k]['info_val'] = get_info_val(stats[k]['value'])
        return stats

    def get(self, request, **kwargs):
        # Retrieve all plugins
        plugins = (
            plugin_api.get_active_plugins('project_app')
            + plugin_api.get_active_plugins('backend')
            + plugin_api.get_active_plugins('site_app')
        )
        plugins.sort(key=lambda p: p.title)
        ret = {}
        for p in plugins:
            try:
                stats = self._get_statistics(p)
                if len(stats):
                    ret[p.name] = {
                        'title': p.title,
                        'icon': p.icon,
                        'stats': stats,
                    }
            except Exception as ex:
                ret[p.name] = {
                    'title': p.title,
                    'icon': p.icon,
                    'error': str(ex),
                }
                logger.error(f'Exception in {p.name}.get_statistics(): {ex}')
        return Response(ret)
