# Generated by Django 5.2.10 on 2026-02-11 15:40

import martor.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('adminalerts', '0001_squashed_0006_adminalert_require_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminalert',
            name='_description_rendered',
        ),
        migrations.RemoveField(
            model_name='adminalert',
            name='description_markup_type',
        ),
        migrations.AlterField(
            model_name='adminalert',
            name='description',
            field=martor.models.MartorField(
                blank=True,
                help_text='Full description of alert (optional, will be shown on a separate page)',
                null=True,
            ),
        ),
    ]
