# Generated by Django 5.2.10 on 2026-03-31 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'adminalerts',
            '0007_remove_adminalert__description_rendered_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlertDismissal',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date_modified',
                    models.DateTimeField(
                        auto_now=True, help_text='DateTime of last modification'
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        help_text='Alert which has been dismissed',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='adminalerts.adminalert',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User who has dismissed the alert',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dismissed_alerts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='adminalert',
            name='dismissed_by',
            field=models.ManyToManyField(
                through='adminalerts.AdminAlertDismissal',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
