# Generated by Django 5.2.10 on 2026-01-20 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('filesfolders', '0001_squashed_0005_alter_foreignkey_fields'),
        ('projectroles', '0041_alter_appsetting_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hyperlink',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(
                fields=('project', 'folder', 'name'),
                name='unique_project_file_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(
                fields=('project', 'folder', 'name'),
                name='unique_project_folder_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='hyperlink',
            constraint=models.UniqueConstraint(
                fields=('project', 'folder', 'name'),
                name='unique_project_hyperlink_name',
            ),
        ),
    ]
