# Generated by Django 5.2.10 on 2026-01-20 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projectroles', '0041_alter_appsetting_unique_together_and_more'),
        ('sodarcache', '0001_squashed_0004_update_jsonfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jsoncacheitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='jsoncacheitem',
            constraint=models.UniqueConstraint(
                fields=('project', 'app_name', 'name'),
                name='unique_project_app_name_cache',
            ),
        ),
    ]
