name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: sodar_core
          POSTGRES_USER: sodar_core
          POSTGRES_PASSWORD: sodar_core
        options: >-
          --health-cmd "pg_isready -U sodar_core"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    env:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
      DATABASE_URL: 'postgres://sodar_core:sodar_core@0.0.0.0/sodar_core'
    steps:
      - name: Install server dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq build-essential zlib1g-dev libtiff5-dev libjpeg8-dev libfreetype6-dev
          sudo apt-get install -qq liblcms2-dev libwebp-dev libpq-dev graphviz-dev
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install project Python dependencies
        run: |
          pip install "wheel>=0.45.1, <0.46"
          pip install -r requirements/base.txt
          pip install -r requirements/test.txt
      - name: Download icons
        run: python manage.py geticons --settings=config.settings.test
      - name: Run collectstatic
        run: python manage.py collectstatic --noinput --settings=config.settings.test
      - name: Run tests
        run: |
          coverage run --rcfile=.coveragerc manage.py test -v 2 --settings=config.settings.test
          coverage lcov
          coverage report
      - name: Check linting
        run: flake8 .
        if: ${{ matrix.python-version == '3.11' }}
      - name: Check formatting
        run: make black arg=--check
        if: ${{ matrix.python-version == '3.11' }}
      - name: Report coverage with Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage.lcov'
          fail-on-error: false
        if: ${{ matrix.python-version == '3.11' }}
